# Generated by Django 4.2.6 on 2023-10-19 18:05

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PersonData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None
                    ),
                ),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "organization",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("location", models.CharField(blank=True, max_length=500, null=True)),
                ("city", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "emails",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=256),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SocialData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instagram", models.CharField(blank=True, max_length=256, null=True)),
                ("facebook", models.CharField(blank=True, max_length=256, null=True)),
                ("tiktok", models.CharField(blank=True, max_length=256, null=True)),
                ("paypal", models.CharField(blank=True, null=True)),
                ("twitter", models.URLField(blank=True, max_length=256, null=True)),
                ("snapchat", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_of_person",
                        to="data.persondata",
                    ),
                ),
            ],
        ),
    ]
